/* AUTOGENERATED DO NOT EDIT */

#ifndef FRAMEWORK_SENSOR_SENSOR_DB_H
#define FRAMEWORK_SENSOR_SENSOR_DB_H

#include "utils_assert.h"

#define SENSOR_MAX_NUM 28

#define SENS_MC_PWM_1 0
#define SENS_MC_PWM_2 1
#define SENS_MC_VOLT_1 2
#define SENS_MC_VOLT_2 3
#define SENS_MC_CURR_1 4
#define SENS_MC_CURR_2 5
#define SENS_MC_RPM_1 6
#define SENS_MC_RPM_2 7
#define SENS_MC_TEMP_CON_1 8
#define SENS_MC_TEMP_CON_2 9
#define SENS_MC_TEMP_MOT_1 10
#define SENS_MC_TEMP_MOT_2 11
#define SENS_BRAKE_PRESSURE 12
#define SENS_BRAKE_POS 13
#define SENS_THROTTLE_POS_1 14
#define SENS_THROTTLE_POS_2 15
#define SENS_STEERING_POS 16
#define SENS_VCU_MCU_TEMP 17
#define SENS_TEMP_R_IN 20
#define SENS_TEMP_R_OUT 21
#define SENS_TEMP_L_IN 22
#define SENS_TEMP_L_OUT 23
#define SENS_PRES_R_IN 24
#define SENS_PRES_R_OUT 25
#define SENS_PRES_L_IN 26
#define SENS_PRES_L_OUT 27

#define SENS_MC_PWM(i) (ASSERT(i>0&&i<=2), -1+i)
#define SENS_MC_VOLT(i) (ASSERT(i>0&&i<=2), 1+i)
#define SENS_MC_CURR(i) (ASSERT(i>0&&i<=2), 3+i)
#define SENS_MC_RPM(i) (ASSERT(i>0&&i<=2), 5+i)
#define SENS_MC_TEMP_CON(i) (ASSERT(i>0&&i<=2), 7+i)
#define SENS_MC_TEMP_MOT(i) (ASSERT(i>0&&i<=2), 9+i)
#define SENS_THROTTLE_POS(i) (ASSERT(i>0&&i<=2), 13+i)

#endif
