#!/usr/bin/env python3

import csv

STORAGE_SIZE = 8192-4

ofst_names = []

with open('param_db.csv', 'r') as csvfile:
    reader = csv.reader(csvfile)
    next(reader)
    for row in reader:
        ofst = int(row[0])
        name = row[1]
        ofst_names.append((ofst,name))


with open('param_db.h', 'w') as header:
    header.write(
"""/* AUTOGENERATED DO NOT EDIT */

#ifndef APP_PARAM_PARAM_DB_H
#define APP_PARAM_PARAM_DB_H

#include "framework/sensor/param_db_calib.h"

struct param_info_t {
	char *name;
	uint32_t offset;
};

extern struct param_info_t param_info[];

""")

    for (ofst, name) in ofst_names:
        header.write("#define PARAM_{} {}\n".format(name.upper(), ofst))

    header.write("#define PARAM_INFO_COUNT ({} + PARAM_INFO_CALIB_COUNT)"
                 .format(len(ofst_names)))

    header.write("\n#endif\n")


with open('param_db.c', 'w') as source:
    source.write(
"""/* AUTOGENERATED DO NOT EDIT */

#include <stdint.h>

#include "param_db.h"
#include "framework/sensor/param_db_calib.c"

""")

    source.write("struct param_info_t param_info[] = {\n")
    for (ofst, name) in ofst_names:
        source.write('\t{{"{}", {}}},\n'.format(name, ofst))
    source.write("\tPARAM_INFO_CALIB\n")
    source.write("};\n")
