/* AUTOGENERATED DO NOT EDIT */

#include <stdint.h>

#include "param_db.h"
#include "framework/sensor/param_db_calib.c.h"

struct param_info_t param_info[] = {
	{"calib_start", 2048},
	{"calib_end", 4096},
	PARAM_INFO_CALIB
};
