/* AUTOGENERATED DO NOT EDIT */

#ifndef APP_PARAM_PARAM_DB_H
#define APP_PARAM_PARAM_DB_H

#include <stdint.h>

struct param_info_t {
	char *name;
	uint32_t offset;
};

#define PARAM_CALIB_START 2048
#define PARAM_CALIB_END 4096

#endif
